### ISSUE TITLE
[nfd] Automatic appending of file extension to saved files

### ISSUE THREAD

**Issue by bazz1tv** [bazz1tv/snestracker#128]
When an NFD Save Prompt has a file extension hint, and the user doesn't manually write in the file extension, it should automatically be appended to the file name.

This is actually something in 3rd party library NativeFileDialog that will need changing.

**Comment by bazzinotti** [comment]
This is not a problem on Mac (10.11), as can be seen in the attached screenshot (v0.1.1)
![Screen Shot 2020-07-27 at 12 12 37 AM](https://user-images.githubusercontent.com/2224787/88502920-01311e00-cf9e-11ea-9fad-ff650762fabd.png)

**Comment by bazzinotti** [comment]
I just fixed this earlier today :D
