### ISSUE TITLE
Numlock ON limits pattern editor functionality

### ISSUE THREAD

**Issue by bazz1tv** [bazz1tv/snestracker#162]
On Windows 10, and possibly other platforms, when the PC keyboard's Numlock function is active, the user cannot edit the Pattern Editor's instrument, volume, effect, and effect parameter columns. At this time, the user needs to ensure that numlock is not on before being able to edit those areas.

**Comment by bazzinotti** [comment]
test

**Comment by bazzinotti** [comment]
fixed :)
