### ISSUE TITLE
Recent Files displays incorrect auto-completed file extension file

### ISSUE THREAD

**Issue by bazz1tv** [bazz1tv/snestracker#173]
SO FIX IT! BAZZ FIX IT POLEASEDKJDFKLLKFDLKDFKLFDSLKSFD:sdflk;

**Comment by bazzinotti** [comment]
Fixed! By the power of believing in myself. I have fixed the bug and believe also that 500 Insects may have been responsible for infecting my project with bugs! Thanks a lot 500 insects! jk I love you and your bug self. <3
